name: notificationapi_flutter_sdk
description: A Flutter plugin for integrating NotificationAPI push notifications into your mobile app.
version: 2.0.5
homepage: https://github.com/notificationapi-com/notificationapi-flutter-sdk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  push: ^3.3.3
  flutter_local_notifications: ^17.2.2
  http: ^1.1.0
  device_info_plus: ^10.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.notificationapi.flutter_sdk
        pluginClass: NotificationapiFlutterSdkPlugin
      ios:
        pluginClass: NotificationapiFlutterSdkPlugin
